# Testing Area for Nico 

## Description
**TASK**

Implement a regression tree algorithm and a random forest algorithm (based on 
the implemented regression tree algorithm) for predicting numeric values– You can find various implementations for these algorithms. However, we can also apply our own ideas for splitting of instances
+ We should implement these algorithms from scratch (not using any part of existing code)
+ We can use existing code/functions for general parts like: Code for reading the input and testing the algorithm (cross- validation, performance metrics for regression...) 

**COMPARISON**

Compare the implemented techniques with the existing implementations of regression trees/random forest and one other existing regression techniques (we may use the default parameters for the existing techniques) 

+ Experiment with at least three configurations (number of trees, ...) for random 
forest
+ Using at least two performance metrics for comparison
+ Applying cross-validation

***Conclusions***
+ How efficient are our algorithms?
+ Performance of our algorithms?
+ Other findings

## Code section

In [2]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

from typing import Literal, Dict, Any, Self
from numpy.typing import ArrayLike

import logging

logging.basicConfig(level=logging.WARNING,
                    format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.WARNING)

The principle of building a Regression Tree follows the same approach as the creation of a Classification Tree.

We search for the feature which splits the target feature values most purely, divide the dataset along the values of this descriptive feature and repeat this process for each of the sub datasets until we accomplish a stopping criteria. If we accomplish a stopping criteria, we grow a leaf node.

Most notable difference is when to stop:
If we now consider the property of our new continuously scaled target feature we mention that the third stopping criteria can no longer be used since the target feature values can now take on an infinite number of different values. Consequently, it is most likely that we will not find pure target feature values until there is only one instance left in the dataset.

Long story short, there is in general nothing like pure target feature values.

To address this issue, we will introduce an early stopping criteria that returns the average value of the target feature values left in the dataset if the number of instances in the dataset is e.g. <= 5.

In [ ]:
class RegressionTreeNico():
    '''
    Custom implementation of a regression decision tree for 
    184.702 Machine Learning (VU 3,0) 2025W

    This class builds a regression tree from scratch and supports both
    categorical and continuous features. It uses variance/MSE reduction
    as the splitting criterion. It also supports recursive tree growth with
    configurable stopping criteria (minimum instances per leaf, maximum depth).

    '''    

    def __init__(self) -> None:
        pass

    def _calc_MSE(self, Y_true: ArrayLike, Y_pred: ArrayLike) -> np.float64:
        '''
        Calculates mean squared error

        Returns:
            MSE of given features
        
        '''
        return np.square(np.subtract(Y_true, Y_pred)).mean()

    def _calc_variance_cat_features(self, data: ArrayLike, target_name: str, which_feature_name: str) -> np.float64:
        '''
        Used to calculate the variance of categorical features to decide which feature to use for the next leaf via minimum variance!

        Parameters
        ----------
        data : ArrayLike
            The data set in which we want to calculate the variance for a given feature
        target_name: str
            Name of the target feature
        which_feature_name: str
            Name of the feature for which we want to calculate the variance.

        Returns
        -------
        np.float64
            The (weighted) variance of the feature in the given data
        '''
        
        # prep building blocks for vectorized variance calculation
        grouped_data = data.groupby(which_feature_name)[target_name]
        sizes = grouped_data.size()
        
        # In case we have only one appearance of a value (size N = 1), 
        # then we have to make sure it makes 0 instead of inf because of the division / (N - 1)
        feature_variances = grouped_data.var(ddof=1).fillna(0) 

        weighted_feature_variances = (sizes / len(data)) * feature_variances

        # return the total weighted variance for the feature
        return weighted_feature_variances.sum()
    
        # old non-vectorized part
        feature_values = np.unique(data[which_feature_name])
        feature_variance = 0

        for value in feature_values:
            subset = data[data[which_feature_name] == value].reset_index()

            # In case we have only one appearance of a value, then we have to make sure it makes 0 instead of inf because of the division / (N - 1)
            if len(subset) <= 1:
                subset_var = 0.0
            else:
                # standard in np.var is divided by N instead of N - 1!
                subset_var = (len(subset)/len(data)) * np.var(subset[target_name], ddof=1)

            feature_variance += subset_var
        
        return feature_variance
    
    def _calc_variance_cont_features(self, data: ArrayLike, target_name: str, which_feature_name: str) -> np.float64:
        '''
        Used to calculate the variance of continous features to decide which feature to use for the next leaf via minimum variance!
        
        Parameters
        ----------
        data : ArrayLike
            The data set in which we want to calculate the variance for a given feature
        target_name: str
            Name of the target feature
        which_feature_name: str
            Name of the feature for which we want to calculate the variance.

        Returns
        -------
        np.float64
            The (weighted) variance of the feature in the given data
        '''   

        # initialize weighted mse
        best_weighted_mse = np.inf
        best_threshold = np.inf
                    
        # sort the data by the feature
        data = data.sort_values(by=which_feature_name)
        X = data[which_feature_name].values
        y = data[target_name].values

        # now do all the things we did in the loop in one step!
        # summing up enables us to calculate for each i in a loop to have the sums/means already:
        
        # left side 
        cum_sum = np.cumsum(y)
        cum_squared_sum = np.cumsum(y**2)
        counts = np.arange(1, len(y) + 1) 
        
        # e.g. for i = 4
        # cum_sum = sum up until 4th row
        # counts = well.. four

        # mse can also be written (after rearranging) as:
        # 1/N * sum_over_i(y_i**2) - mean**2
        left_mean = cum_sum[:-1] / counts[:-1] # -1: everything but the last as this would be the total sum
        left_mse = (cum_squared_sum[:-1] / counts [:-1]) - left_mean**2 
        
        # total values as prep for right side 
        total_sum = cum_sum[-1]
        total_squared_sum = cum_squared_sum[-1]
        total_count = len(y)

        # right side
        right_sum = total_sum - cum_sum[:-1]
        right_sq_sum = total_squared_sum - cum_squared_sum[:-1]
        right_count = total_count - counts[:-1]

        right_mean = right_sum / right_count
        right_mse = (right_sq_sum / right_count) - right_mean**2

        # weighted MSE for all the different splits
        weighted_mse = (counts[:-1] * left_mse + right_count * right_mse) / total_count

        # "consecutive" rows for the threshold (basically shifting the X up and down visually to overlap consecutively)
        threshold = (X[1:] + X[:-1]) / 2

        best_split = np.argmin(weighted_mse)

        # return the best wmse as well as the threshold
        return weighted_mse[best_split], threshold[best_split]

        # find here the "old" for loop for the exact same functionality as above!

        # compute the mse at current node
        current_yhat = np.mean(data[target_name].mean())
        current_mse = self._calc_MSE(data[target_name], current_yhat)
        current_mse = np.round(current_mse, 3)

        # iterate over all rows of the SORTED data
        for i in range(1, len(data)):
            logger.info(data)
            logger.info(which_feature_name)
            logger.info(f"{data.iloc[i][which_feature_name]}, {data.iloc[i-1][which_feature_name]}")
            # compute average of two consecutive rows to have some threshold start 
            split_val = (data.iloc[i][which_feature_name] + data.iloc[i-1][which_feature_name]) / 2

            # split the data into the two sides
            left_branch = data[data[which_feature_name]<=split_val]
            right_branch = data[data[which_feature_name]>split_val]

            # compute the MSE of both sides
            left_yhat = np.mean(left_branch[target_name]) 
            left_mse = self._calc_MSE(left_branch[target_name], left_yhat) 

            right_yhat = np.mean(right_branch[target_name]) 
            right_mse = self._calc_MSE(right_branch[target_name], right_yhat) 

            # compute weighted MSE
            weighted_mse = ((len(left_branch) * left_mse) + (len(right_branch) * right_mse))/len(data)

            # update bestbest_weighted_mse
            if weighted_mse <= best_weighted_mse:
                best_weighted_mse = weighted_mse
                best_threshold = split_val

        return best_weighted_mse, best_threshold

    def _calc_entropy(self, target_column: str) -> np.float64:
        '''
        Calculate the entropy of a target column
       
        Parameters
        ----------
        target_column : ArrayLike
            The target column of which we want to calculate the entropy

        Returns
        -------
        np.float64
            The entropy of the given target column    
        '''

        elements, counts = np.unique(target_column, return_counts = True)

        entropy = np.sum([(-counts[i]/np.sum(counts)) * np.log2(counts[i] / np.sum(counts)) for i in range(len(elements))])
        
        return entropy
    
    def _calc_information_gain(self, data: ArrayLike, target_name:str, which_feature_name: str) -> np.float64:
        '''
        Calculate the information gain based on an attribute (with its weighted entropy!) and the target variable entropy
        
        Parameters
        ----------
        data : ArrayLike
            The data set in which we want to calculate the information gain for a given feature
        target_name: str
            Name of the target feature
        which_feature_name: str
            Name of the feature for which we want to calculate the information gain.

        Returns
        -------
        np.float64
            The infomation gain of the given column    
        '''
        target_entropy = self._calc_entropy(data[target_name])

        vals, counts = np.unique(data[which_feature_name], return_counts=True)

        # Calculate the WEIGHTED entropy
        weighted_entropy = np.sum([(counts[i] / np.sum(counts)) * self._calc_entropy(data[data[which_feature_name]==vals[i]].dropna()[target_name]) for i in range(len(vals))])
    
        # Calculate the information gain
        information_gain = target_entropy - weighted_entropy
        
        return information_gain

    def _find_best_split(self, data: pd.DataFrame, target_name: str, categorical_features:list = []) -> Dict:
        best_feature = None
        best_threshold = None
        best_variance = np.inf
        is_continuous = False

        for feature_name in data.columns:
            logger.info(f"passed categorical_features: {categorical_features}")
            if feature_name == target_name:
                continue

            elif feature_name in categorical_features:
                logger.info(f"feature {feature_name} entered categorical processing step")
                variance = self._calc_variance_cat_features(data, target_name, feature_name)
                
                # if improvement: overwrite values
                if variance <= best_variance:
                    best_feature = feature_name
                    best_threshold = None
                    best_variance = variance
                    is_continuous = False
            
            else:
                logger.info(f"feature {feature_name} entered continous processing step")

                variance, threshold = self._calc_variance_cont_features(data, target_name, feature_name)
                                
                # if improvement: overwrite values
                if variance <= best_variance:
                    best_feature = feature_name
                    best_threshold = threshold
                    best_variance = variance
                    is_continuous = True
        
        return best_feature, best_threshold, best_variance, is_continuous

    def _Classfier(
            self, 
            data: pd.DataFrame, 
            target_name: str, 
            min_instances: int = 1, 
            categorical_features: list = [], 
            max_depth: int = None, 
            features: list = None,
            depth: int = 0) -> dict[str, Any]:
        '''
        Recursive tree building algorithm.

        Parameters
        ----------
        data : pd.DataFrame
            Subset of the dataset at the current node.
        target_name : str
            Name of the target column
        min_instances : int, optional
            Minimum number of samples required to allow further splitting, else mean is taken.
        categorical_features : list, optional (but actually necessary in case of such)
            List of feature names that represent categorical features
        max_depth : int, optional
            Maximum depth of the tree. If None, the tree grows until min_instances is reached
        features : list, optional
            List of (remaining) features available for splitting
        depth : int, optional
            Depth of the recursion. Used internally

        Returns
        -------
        dict[str, Any] or float
            A nested dictionary representing the tree structure. 
            "Any" will be another such dictionary or a float (= mean target value) if the leaf node is reached

        
        '''
        # Stopping criterion for the recurrsion if we require some minimum value for the size/length of a sub dataset
        if len(data) <= min_instances:
            return np.mean(data[target_name])
    
        # If the dataset has reached the wished for tdepth, return the mean target feature value of the remaining dataset as before
        elif max_depth != None and depth >= max_depth:
            return np.mean(data[target_name])

        # Now this is the actual "tree growing" part
        else:
            # get the best split
            best_feature, best_threshold, best_variance, is_continuous = self._find_best_split(data, target_name, categorical_features)

            features = list(data.columns)
            features.remove(target_name)

            # Small fallback in case of no best value found
            if best_feature == None:
                logger.info(f"No best feature to split on found. \nDepth: {depth} \nFeatures left: {features} ")
                return np.mean(data[target_name])

            if is_continuous:
                # build the branching for continous variables
                left_branch = data[data[best_feature] <= best_threshold]
                right_branch = data[data[best_feature] > best_threshold]
                
                ''' Structure for continous feature split:
                {
                    "feature": "X1",
                    "threshold": 400,
                    "left": { subtree(s) for X <= 400 or value in case we reached conditions (ie leaf node) above},
                    "right": { subtree(s) for X > 400 or value in case we reached conditions (ie leaf node) above}
                }   
                '''
                logger.warning(f"Depth {depth}, feature {best_feature}, threshold {best_threshold}, "
                            f"left={len(left_branch)}, right={len(right_branch)}")
                return {
                    "feature": best_feature,
                    "threshold": best_threshold,
                    "left": self._Classfier(data=left_branch, 
                                            target_name=target_name, 
                                            categorical_features=categorical_features,
                                            min_instances=min_instances, 
                                            max_depth=max_depth, 
                                            depth= depth+1),
                    "right": self._Classfier(data=right_branch, 
                                             target_name=target_name, 
                                             categorical_features=categorical_features,
                                             min_instances=min_instances, 
                                             max_depth=max_depth, 
                                             depth= depth+1)
                }
            
            else:
                branches = {}
                for val in np.unique(data[best_feature]):
                    subset = data[data[best_feature] == val]

                    # If subset is the sane as parent, stop recursion as this gets stuck if the one var is always the best split
                    if len(subset) == len(data):
                        branches[val] = float(np.mean(data[target_name]))
                        continue

                    # keep this safeguard info here if we hit some weird recurssion depth issue again
                    if depth > 100:
                        logger.warning(f"Depth {depth}, value {val}, best_feature {best_feature}, lendata {len(data)}")
                    
                    branches[val] = self._Classfier(data=subset, 
                                                    target_name=target_name, 
                                                    categorical_features=categorical_features,
                                                    min_instances=min_instances, 
                                                    max_depth=max_depth, 
                                                    depth= depth+1)
                
                ''' Structure for non-continous feature split:
                {
                    "feature": "categoryXY",
                    "branches": { 
                        "X": subtree(s) for value "X" of feature categoryXY,
                        "Y": subtree(s) for value "Y" of feature categoryXY
                    }
                }   
                '''
                
                return {
                    "feature": best_feature,
                    "branches": branches
                }
    
    def fit(self, 
            data: pd.DataFrame, 
            target_name: str, 
            min_instances: int = 1,
            max_depth: int = None,
            categorical_features: list = []) -> Self:
            
        '''
        Creates ("fits") the regression tree to the given dataset.

        Parameters
        ----------
        data : pd.DataFrame
            Training dataset containing features AND the target
        target_name : str
            Name of the target column
        min_instances : int, optional
            Minimum number of samples required to allow further splitting, else mean is taken.
        max_depth : int, optional
            Maximum depth of the tree. If None, the tree grows until min_instances is reached
        categorical_features : list, optional (but actually necessary in case of such)
            List of feature names that represent categorical features

        Returns
        -------
        Self
            Stores the learned tree in `self.tree_` of the initialized instance of this class.
        '''

        self.target_name = target_name
        self.categorical_features = categorical_features
        self.max_depth = max_depth
        self.min_instances = min_instances
        self.tree_ = self._Classfier(
            data, target_name, categorical_features=categorical_features, min_instances=min_instances, max_depth=max_depth
        )
        return self

    def _predict_row(self, X_pred: ArrayLike, tree:dict, features:list, categorical_features: list = []):
        logger.info(f"Entering _predict_row with (sub)tree: {tree}")
        logger.info(f"X_pred row: {X_pred}")
        logger.info(f"categorical_features passed to _predict_row: {categorical_features}")
        
        if tree["feature"] in features:
            feature = tree["feature"]
            logger.info(f"Checking for feature: {feature}\ncategorical features passed: {categorical_features}")

            if feature in categorical_features:
                result = tree["branches"][X_pred[feature]]
            else:
                threshold = tree["threshold"]
                logger.info(f"feature: {feature} // feature_value: {X_pred[feature]} // threshold: {threshold}")
                result = tree["left"] if X_pred[feature] <= threshold else tree["right"]
            
            logger.info(f"result: {result}")
            
            # continue if not a leaf
            if isinstance(result, dict):
                return self._predict_row(X_pred, result, features, categorical_features) #.drop(feature)
            # if we get a value then return and "break" the recurssion
            else:
                if isinstance(result, (np.float64, float)):
                    return result
                else:
                    logging.error(f"result is not of type float, type: {type(result)}")
                    raise ValueError(f"result is not of type float, type: {type(result)}")

    def _predict_vectorized(self, X_pred: ArrayLike, tree:dict) -> np.ndarray:
        # return the leaf of the subset once reached!
        if not isinstance(tree, dict):
            return np.full(len(X_pred), float(tree))
        
        feature = tree["feature"]

        if "branches" in tree:
            # initialize empty result np array
            y_pred = np.empty(len(X_pred))
            for val, branch in tree["branches"].items():
                mask = X_pred[feature] == val

                # if the mask only contains False, do not go into an infinite loop!
                if not mask.any():
                    continue

                y_pred[mask] = self._predict_vectorized(X_pred[mask], branch)
            return y_pred
        
        elif "threshold" in tree:
            # initialize empty result np array
            y_pred = np.empty(len(X_pred))
            threshold = tree["threshold"]
            mask = X_pred[feature] <= threshold

            # left branch (same condition as before, only go in if we have a non-empty mask)
            if mask.any():
                y_pred[mask] = self._predict_vectorized(X_pred[mask], tree["left"])
            # right branch  
            if (~mask).any():
                y_pred[~mask] = self._predict_vectorized(X_pred[~mask], tree["right"])
            return y_pred
            
        #except Exception as e:
        #    if (len(categorical_features) == 0) and ("branches" in tree): 
        #        logger.error("Categorical feature detected and no categorical_features list passed!")
        #        raise e
        #    raise e
        


    def predict(self, X_pred: ArrayLike, categorical_features: list = []) -> pd.Series:
        '''
        Vectorized prediction using the fitted regression tree.

        Parameters
        -------
        X_pred : pd.DataFrame
            Input samples with the same columns used during training
        categorical_features : list, optional (but actually necessary in case of such)
            List of feature names that represent categorical features
        
        Returns
        -------

        '''
        y_pred = self._predict_vectorized(X_pred, self.tree_)
        # to flatten the np.array and to get an output like with predict_old 
        return pd.Series(y_pred)


    def predict_old(self, X_pred: ArrayLike, categorical_features: list = []) -> pd.Series:
        '''
        "old" or rather initial implementation with row-wise .apply() execution.
        Quite a bit slower than vectorized operations (ofc)

        Parameters
        -------
        X_pred : pd.DataFrame
            Input samples with the same columns used during training
        categorical_features : list, optional (but actually necessary in case of such)
            List of feature names that represent categorical features
        
        Returns
        -------


        '''

        features = X_pred.columns
        result = X_pred.apply(self._predict_row, args=(self.tree_, features, categorical_features), axis=1)
        return result

## Testing Area

In [53]:
# "test" data

# continous example
np.random.seed(0)

a, b, c = 1, 2, 3
n = 100 
x = np.linspace(-10, 10, n)  # feature values from -10 to 10
noise = np.random.normal(0, 10, n)  # some random noise
y = a * x**2 + b * x + c + noise  # quadratic equation with noise

df_continous = pd.DataFrame({'X': x, 'y': y})

# categorical examples
df_small = pd.DataFrame({'Number_of_Bedrooms':[2,2,4,1,3,1,4,2],'Price_of_Sale':[100000,120000,250000,80000,220000,170000,500000,75000]})

df = pd.read_csv("day.csv",usecols=['season','holiday','weekday','weathersit','cnt'])
df_example = df.sample(frac=0.012)

In [54]:
df["weathersit"].unique()

array([2, 1, 3])

In [55]:
testTree = RegressionTreeNico()
treee = testTree.fit(df, categorical_features=["season", "holiday", "weekday", "weathersit"], target_name="cnt")

data_encoded = pd.get_dummies(df[["season", "holiday", "weekday", "weathersit"]], drop_first=True)
sk_tree = DecisionTreeRegressor(random_state=42)
sk_tree.fit(data_encoded, df["cnt"])
y_pred = sk_tree.predict(df.drop("cnt", axis=1))

y_pred

array([2365.        , 2485.16666667, 2968.92857143, 3339.625     ,
       3355.76923077, 2992.375     , 2837.53333333, 2365.        ,
       2156.38095238, 2968.92857143, 1920.75      , 3355.76923077,
       2992.375     , 2881.90909091, 2365.        , 2156.38095238,
       1053.5       , 1920.75      , 2070.5       , 2981.75      ,
       2881.90909091, 2490.875     , 2156.38095238, 2968.92857143,
       1920.75      ,  473.5       , 2992.375     , 2837.53333333,
       2490.875     , 2156.38095238, 1900.66666667, 1920.75      ,
       2070.5       , 2992.375     , 2837.53333333, 2365.        ,
       2156.38095238, 2968.92857143, 3339.625     , 2070.5       ,
       2992.375     , 2881.90909091, 2490.875     , 2156.38095238,
       2968.92857143, 3339.625     , 3355.76923077, 2992.375     ,
       2881.90909091, 2490.875     , 2156.38095238, 1053.5       ,
       3339.625     , 3355.76923077, 2981.75      , 2837.53333333,
       2490.875     , 2156.38095238, 1900.66666667, 3339.625     ,
       3355.76923077, 2992.375     , 2837.53333333, 2365.        ,
       2485.16666667, 2968.92857143, 3339.625     , 2070.5       ,
        623.        , 2837.53333333, 2490.875     , 2156.38095238,
       2968.92857143, 1920.75      , 2070.5       , 2992.375     ,
       2881.90909091, 2490.875     , 2156.38095238, 4344.5       ,
       5051.5       , 3965.16666667, 4232.42857143, 5846.22222222,
       6178.35294118, 4372.9       , 4550.83333333, 5051.5       ,
       3965.16666667, 1685.        , 3919.14285714, 4107.75      ,
       5659.6       , 4550.83333333, 4560.66666667, 5531.        ,
       5771.94444444, 3919.14285714, 4107.75      , 4372.9       ,
       4344.5       , 4560.66666667, 3965.16666667, 5771.94444444,
       3126.        ,  795.        , 5659.6       , 4550.83333333,
       4560.66666667, 5531.        , 5771.94444444, 3919.14285714,
       4107.75      , 4372.9       , 4550.83333333, 5051.5       ,
       3965.16666667, 4232.42857143, 5846.22222222, 6178.35294118,
       4372.9       , 4344.5       , 4560.66666667, 3965.16666667,
       5771.94444444, 5846.22222222, 6178.35294118, 5659.6       ,
       4550.83333333, 5051.5       , 5531.        , 5771.94444444,
       3919.14285714, 4107.75      , 4372.9       , 4550.83333333,
       4560.66666667, 3965.16666667, 4232.42857143, 5846.22222222,
       6178.35294118, 5659.6       , 4344.5       , 4560.66666667,
       5531.        , 5771.94444444, 5846.22222222, 6178.35294118,
       5659.6       , 5503.66666667, 5051.5       , 3965.16666667,
       5771.94444444, 5846.22222222, 6178.35294118, 4372.9       ,
       4550.83333333, 5051.5       , 5531.        , 4232.42857143,
       5846.22222222, 6178.35294118, 5659.6       , 4550.83333333,
       5051.5       , 5531.        , 4232.42857143, 5846.22222222,
       6178.35294118, 4372.9       , 4344.5       , 5222.4       ,
       6054.31818182, 4478.42857143, 5890.05882353, 5931.05882353,
       5346.9       , 6038.        , 5899.66666667, 6054.31818182,
       6318.5       , 5890.05882353, 5931.05882353, 5248.83333333,
       4697.        , 5899.66666667, 6054.31818182, 6318.5       ,
       5513.6       , 5931.05882353, 5346.9       , 5567.70588235,
       5899.66666667, 6054.31818182, 6318.5       , 5890.05882353,
       5931.05882353, 5346.9       , 5567.70588235, 5899.66666667,
       6054.31818182, 4478.42857143, 5890.05882353, 5931.05882353,
       5346.9       , 5567.70588235, 5899.66666667, 6054.31818182,
       6318.5       , 5890.05882353, 5931.05882353, 5346.9       ,
       5567.70588235, 5899.66666667, 5153.33333333, 4478.42857143,
       5890.05882353, 5056.33333333, 5346.9       , 5567.70588235,
       5899.66666667, 6054.31818182, 6318.5       , 5890.05882353,
       5056.33333333, 5248.83333333, 5567.70588235, 5899.66666667,
       6054.31818182, 6318.5       , 5513.6       , 5931.05882353,
       5346.9       , 5567.70588235, 5899.66666667, 6054.31818182,
       4478.42857143, 5890.05882353, 5056.33333333, 5346.9       ,
       5567.70588235, 5899.66666667, 6054.31818182, 6318.5       ,
       5513.6       , 5931.05882353, 5346.9       , 4697.        ,
       2710.        , 1996.        , 1842.        , 5513.6       ,
       5931.05882353, 5346.9       , 5567.70588235, 5899.66666667,
       6054.31818182, 4478.42857143, 5513.6       , 5056.33333333,
       5346.9       , 6038.        , 5222.4       , 5153.33333333,
       4478.42857143, 4744.44444444, 4907.71428571, 3885.        ,
       4989.75      , 4247.16666667, 4699.875     , 4903.36363636,
       5093.26666667, 4907.71428571, 3885.        , 4989.75      ,
       5575.09090909, 5708.38461538, 4903.36363636, 5093.26666667,
       5157.05882353, 4703.94444444, 5693.        , 4247.16666667,
       1840.5       , 5034.58333333, 4744.44444444, 5157.05882353,
       4703.94444444, 4815.46153846, 4247.16666667, 1840.5       ,
       4903.36363636, 5093.26666667, 5157.05882353, 4703.94444444,
       4815.46153846, 5575.09090909, 4699.875     , 5034.58333333,
       4744.44444444,  627.        , 4703.94444444, 4815.46153846,
       5575.09090909, 5708.38461538, 4903.36363636, 4744.44444444,
       5157.05882353, 4703.94444444, 4815.46153846, 5575.09090909,
       5708.38461538, 5034.58333333, 3368.        , 5157.05882353,
       4703.94444444, 4815.46153846, 4247.16666667, 1840.5       ,
       5034.58333333, 5093.26666667, 5157.05882353, 3885.        ,
       1393.5       , 2946.66666667, 4699.875     , 1960.        ,
       5093.26666667, 5157.05882353, 4703.94444444, 4815.46153846,
       4247.16666667, 5708.38461538, 4903.36363636, 5093.26666667,
       5157.05882353, 4703.94444444, 4989.75      , 2946.66666667,
       1840.5       , 4903.36363636, 5093.26666667, 5157.05882353,
       4703.94444444, 4815.46153846, 5575.09090909, 4699.875     ,
       5034.58333333, 4744.44444444, 4907.71428571, 4703.94444444,
       4815.46153846, 4247.16666667, 2070.5       , 2981.75      ,
       2881.90909091, 2490.875     , 2156.38095238, 2173.75      ,
       1920.75      , 3355.76923077, 2992.375     , 2881.90909091,
       2490.875     , 2156.38095238, 2173.75      , 3339.625     ,
       2070.5       , 2992.375     , 2881.90909091, 2490.875     ,
       2156.38095238, 1900.66666667, 3339.625     , 2070.5       ,
       2981.75      , 2881.90909091, 2490.875     , 2156.38095238,
       2173.75      , 1920.75      , 3355.76923077, 2992.375     ,
       2837.53333333, 2365.        , 2485.16666667, 1900.66666667,
       3339.625     , 3355.76923077, 2981.75      , 2837.53333333,
       2490.875     , 2156.38095238, 2968.92857143, 3339.625     ,
       3355.76923077, 2981.75      , 2881.90909091, 2365.        ,
       2485.16666667, 2968.92857143, 3339.625     , 2070.5       ,
       2992.375     , 2837.53333333, 2169.        , 2156.38095238,
       2968.92857143, 1920.75      , 3355.76923077, 2981.75      ,
       2881.90909091, 2490.875     , 2485.16666667, 2173.75      ,
       3339.625     , 3355.76923077, 2992.375     , 2837.53333333,
       2490.875     , 2156.38095238, 2968.92857143, 3339.625     ,
       2070.5       , 2992.375     , 2837.53333333, 2365.        ,
       2156.38095238, 2968.92857143, 3339.625     , 3355.76923077,
       2992.375     , 2837.53333333, 2490.875     , 2156.38095238,
       2968.92857143, 3339.625     , 3355.76923077, 2992.375     ,
       2837.53333333, 2365.        , 2485.16666667, 2968.92857143,
       3339.625     , 3965.16666667, 5771.94444444, 3919.14285714,
       4107.75      , 4372.9       , 4550.83333333, 5051.5       ,
       5531.        , 5771.94444444, 3919.14285714, 4107.75      ,
       4372.9       , 4550.83333333, 5051.5       , 5531.        ,
       5771.94444444, 5846.22222222, 6178.35294118, 5659.6       ,
       4550.83333333, 5051.5       , 5531.        , 5771.94444444,
       5846.22222222, 6178.35294118, 5659.6       , 5503.66666667,
       5051.5       , 3965.16666667, 5771.94444444, 5846.22222222,
       6178.35294118, 1027.        , 4344.5       , 5051.5       ,
       5531.        , 4232.42857143, 5846.22222222, 4107.75      ,
       5659.6       , 4344.5       , 4560.66666667, 5531.        ,
       4232.42857143, 5846.22222222, 4107.75      , 4372.9       ,
       4344.5       , 4560.66666667, 3965.16666667, 5771.94444444,
       5846.22222222, 6178.35294118, 5659.6       , 4344.5       ,
       4560.66666667, 5531.        , 5771.94444444, 5846.22222222,
       6178.35294118, 5659.6       , 4344.5       , 4560.66666667,
       3965.16666667, 5771.94444444, 5846.22222222, 6178.35294118,
       5659.6       , 5503.66666667, 5051.5       , 3965.16666667,
       5771.94444444, 3919.14285714, 6178.35294118, 5659.6       ,
       4550.83333333, 4560.66666667, 5531.        , 5771.94444444,
       5846.22222222, 6178.35294118, 5659.6       , 4344.5       ,
       4560.66666667, 5531.        , 5771.94444444, 5846.22222222,
       6178.35294118, 5659.6       , 4344.5       , 5051.5       ,
       5531.        , 6318.5       , 5890.05882353, 5931.05882353,
       5346.9       , 5567.70588235, 5899.66666667, 6054.31818182,
       6318.5       , 5890.05882353, 5931.05882353, 5346.9       ,
       5567.70588235, 5899.66666667, 7403.        , 6318.5       ,
       5890.05882353, 5931.05882353, 5346.9       , 6038.        ,
       5222.4       , 6054.31818182, 6318.5       , 5513.6       ,
       5056.33333333, 5346.9       , 5567.70588235, 5899.66666667,
       6054.31818182, 6318.5       , 5513.6       , 4459.        ,
       5248.83333333, 5567.70588235, 5899.66666667, 6054.31818182,
       6318.5       , 5890.05882353, 5931.05882353, 5346.9       ,
       5567.70588235, 5899.66666667, 6054.31818182, 6318.5       ,
       5513.6       , 5931.05882353, 5346.9       , 6038.        ,
       5222.4       , 5153.33333333, 6318.5       , 5513.6       ,
       5056.33333333, 5346.9       , 5567.70588235, 5899.66666667,
       6054.31818182, 6318.5       , 5890.05882353, 5931.05882353,
       5248.83333333, 6038.        , 5899.66666667, 6054.31818182,
       6318.5       , 5513.6       , 5056.33333333, 5248.83333333,
       5567.70588235, 5899.66666667, 6054.31818182, 6318.5       ,
       5890.05882353, 5056.33333333, 5248.83333333, 6034.        ,
       5899.66666667, 6054.31818182, 4478.42857143, 5890.05882353,
       5056.33333333, 5346.9       , 5567.70588235, 5899.66666667,
       6054.31818182, 6318.5       , 5890.05882353, 5931.05882353,
       5346.9       , 6038.        , 5222.4       , 6054.31818182,
       6318.5       , 5890.05882353, 5931.05882353, 4703.94444444,
       4815.46153846, 5575.09090909, 5708.38461538, 5034.58333333,
       4744.44444444, 5157.05882353, 4703.94444444, 4989.75      ,
       2946.66666667, 4699.875     , 5034.58333333, 5093.26666667,
       5157.05882353, 3885.        , 5478.        , 4247.16666667,
       5708.38461538, 4903.36363636, 5093.26666667, 5157.05882353,
       4703.94444444, 4989.75      , 5575.09090909, 5708.38461538,
       5034.58333333, 4744.44444444, 5157.05882353, 4703.94444444,
       4815.46153846, 5575.09090909, 5708.38461538, 5034.58333333,
       4744.44444444, 4907.71428571, 3885.        , 1393.5       ,
       4247.16666667, 4699.875     , 5034.58333333, 5093.26666667,
       4907.71428571, 4703.94444444, 4815.46153846, 5575.09090909,
       4699.875     , 4903.36363636, 5093.26666667, 5157.05882353,
       4703.94444444, 5693.        , 4247.16666667, 5708.38461538,
       5034.58333333, 5093.26666667, 5157.05882353, 4703.94444444,
       4989.75      , 4247.16666667, 5708.38461538, 1960.        ,
       5093.26666667, 5157.05882353, 4703.94444444, 4815.46153846,
       4247.16666667, 5708.38461538, 4903.36363636, 5093.26666667,
       4907.71428571, 3885.        , 4815.46153846, 5575.09090909,
       5708.38461538, 4903.36363636, 4744.44444444, 4907.71428571,
       3885.        , 4989.75      , 4247.16666667, 4699.875     ,
       4903.36363636, 5093.26666667, 5157.05882353, 3885.        ,
       4989.75      , 5575.09090909, 5708.38461538, 5034.58333333,
       2837.53333333, 2490.875     , 2156.38095238, 1900.66666667,
       1013.        ,  473.5       , 2981.75      , 2837.53333333,
       2365.        , 2156.38095238, 1900.66666667])

In [56]:
y_pred_custom = treee.predict(df.drop("cnt", axis=1))
y_pred_custom

0      2419.888889
1      2419.888889
2      2968.928571
3      3339.625000
4      3355.769231
          ...
726    2419.888889
727    2419.888889
728    2419.888889
729    2156.380952
730    2419.888889
Length: 731, dtype: float64

In [57]:
y_pred_custom_old = treee.predict_old(df.drop("cnt", axis=1), categorical_features=["season", "holiday", "weekday", "weathersit"])

In [58]:
# check whether output of new and old prediction is the same
check = pd.DataFrame(y_pred_custom_old == y_pred_custom)
check[check[0] == False]

Empty DataFrame
Columns: [0]
Index: []

In [59]:
df_continous

            X           y
0  -10.000000  100.640523
1   -9.797980   83.406021
2   -9.595960   85.677901
3   -9.393939   94.867151
4   -9.191919   87.783120
..        ...         ...
95   9.191919  112.940948
96   9.393939  110.138976
97   9.595960  132.133065
98   9.797980  119.865489
99  10.000000  127.019894

[100 rows x 2 columns]

In [60]:
testTree = RegressionTreeNico()
treee = testTree.fit(df_continous,target_name="y")
y_pred_custom = treee.predict(pd.DataFrame(df_continous.drop("y", axis=1)))

sk_tree = DecisionTreeRegressor(random_state=42)
sk_tree.fit(df_continous.drop("y", axis=1), df_continous["y"])
y_pred = sk_tree.predict(df_continous.drop("y", axis=1))

check = pd.DataFrame(pd.Series(y_pred) == y_pred_custom)
check[check[0] == False]

2025-12-02 13:34:20,714 - WARNING - Depth 0, feature X, threshold 6.8686868686868685, left=84, right=16
2025-12-02 13:34:20,716 - WARNING - Depth 1, feature X, threshold -6.666666666666667, left=17, right=67
2025-12-02 13:34:20,719 - WARNING - Depth 2, feature X, threshold -9.09090909090909, left=5, right=12
2025-12-02 13:34:20,722 - WARNING - Depth 3, feature X, threshold -9.8989898989899, left=1, right=4
2025-12-02 13:34:20,728 - WARNING - Depth 4, feature X, threshold -9.494949494949495, left=2, right=2
2025-12-02 13:34:20,734 - WARNING - Depth 5, feature X, threshold -9.696969696969695, left=1, right=1
2025-12-02 13:34:20,736 - WARNING - Depth 5, feature X, threshold -9.292929292929294, left=1, right=1
2025-12-02 13:34:20,738 - WARNING - Depth 3, feature X, threshold -7.474747474747475, left=8, right=4
2025-12-02 13:34:20,739 - WARNING - Depth 4, feature X, threshold -8.686868686868687, left=2, right=6
2025-12-02 13:34:20,740 - WARNING - Depth 5, feature X, threshold -8.88888888888889, left=1, right=1
2025-12-02 13:34:20,741 - WARNING - Depth 5, feature X, threshold -7.6767676767676765, left=5, right=1
2025-12-02 13:34:20,742 - WARNING - Depth 6, feature X, threshold -7.878787878787879, left=4, right=1
2025-12-02 13:34:20,743 - WARNING - Depth 7, feature X, threshold -8.08080808080808, left=3, right=1
2025-12-02 13:34:20,743 - WARNING - Depth 8, feature X, threshold -8.484848484848484, left=1, right=2
2025-12-02 13:34:20,744 - WARNING - Depth 9, feature X, threshold -8.282828282828284, left=1, right=1
2025-12-02 13:34:20,745 - WARNING - Depth 4, feature X, threshold -6.8686868686868685, left=3, right=1
2025-12-02 13:34:20,746 - WARNING - Depth 5, feature X, threshold -7.070707070707071, left=2, right=1
2025-12-02 13:34:20,747 - WARNING - Depth 6, feature X, threshold -7.2727272727272725, left=1, right=1
2025-12-02 13:34:20,749 - WARNING - Depth 2, feature X, threshold 3.8383838383838382, left=52, right=15
2025-12-02 13:34:20,750 - WARNING - Depth 3, feature X, threshold -4.040404040404041, left=13, right=39
2025-12-02 13:34:20,750 - WARNING - Depth 4, feature X, threshold -6.262626262626263, left=2, right=11
2025-12-02 13:34:20,751 - WARNING - Depth 5, feature X, threshold -6.4646464646464645, left=1, right=1
2025-12-02 13:34:20,752 - WARNING - Depth 5, feature X, threshold -5.858585858585858, left=2, right=9
2025-12-02 13:34:20,752 - WARNING - Depth 6, feature X, threshold -6.0606060606060606, left=1, right=1
2025-12-02 13:34:20,753 - WARNING - Depth 6, feature X, threshold -5.05050505050505, left=4, right=5
2025-12-02 13:34:20,753 - WARNING - Depth 7, feature X, threshold -5.252525252525253, left=3, right=1
2025-12-02 13:34:20,754 - WARNING - Depth 8, feature X, threshold -5.454545454545455, left=2, right=1
2025-12-02 13:34:20,754 - WARNING - Depth 9, feature X, threshold -5.656565656565657, left=1, right=1
2025-12-02 13:34:20,755 - WARNING - Depth 7, feature X, threshold -4.444444444444445, left=3, right=2
2025-12-02 13:34:20,755 - WARNING - Depth 8, feature X, threshold -4.848484848484849, left=1, right=2
2025-12-02 13:34:20,756 - WARNING - Depth 9, feature X, threshold -4.646464646464647, left=1, right=1
2025-12-02 13:34:20,756 - WARNING - Depth 8, feature X, threshold -4.242424242424242, left=1, right=1
2025-12-02 13:34:20,757 - WARNING - Depth 4, feature X, threshold 2.828282828282828, left=34, right=5
2025-12-02 13:34:20,757 - WARNING - Depth 5, feature X, threshold 0.808080808080808, left=24, right=10
2025-12-02 13:34:20,757 - WARNING - Depth 6, feature X, threshold -2.4242424242424243, left=8, right=16
2025-12-02 13:34:20,758 - WARNING - Depth 7, feature X, threshold -2.8282828282828283, left=6, right=2
2025-12-02 13:34:20,758 - WARNING - Depth 8, feature X, threshold -3.6363636363636367, left=2, right=4
2025-12-02 13:34:20,759 - WARNING - Depth 9, feature X, threshold -3.8383838383838387, left=1, right=1
2025-12-02 13:34:20,759 - WARNING - Depth 9, feature X, threshold -3.2323232323232323, left=2, right=2
2025-12-02 13:34:20,760 - WARNING - Depth 10, feature X, threshold -3.4343434343434343, left=1, right=1
2025-12-02 13:34:20,760 - WARNING - Depth 10, feature X, threshold -3.0303030303030303, left=1, right=1
2025-12-02 13:34:20,760 - WARNING - Depth 8, feature X, threshold -2.6262626262626263, left=1, right=1
2025-12-02 13:34:20,761 - WARNING - Depth 7, feature X, threshold -1.4141414141414144, left=5, right=11
2025-12-02 13:34:20,761 - WARNING - Depth 8, feature X, threshold -2.02020202020202, left=2, right=3
2025-12-02 13:34:20,762 - WARNING - Depth 9, feature X, threshold -2.2222222222222223, left=1, right=1
2025-12-02 13:34:20,762 - WARNING - Depth 9, feature X, threshold -1.8181818181818183, left=1, right=2
2025-12-02 13:34:20,762 - WARNING - Depth 10, feature X, threshold -1.6161616161616168, left=1, right=1
2025-12-02 13:34:20,763 - WARNING - Depth 8, feature X, threshold -1.212121212121212, left=1, right=10
2025-12-02 13:34:20,763 - WARNING - Depth 9, feature X, threshold -0.6060606060606064, left=3, right=7
2025-12-02 13:34:20,764 - WARNING - Depth 10, feature X, threshold -0.8080808080808088, left=2, right=1
2025-12-02 13:34:20,765 - WARNING - Depth 11, feature X, threshold -1.0101010101010104, left=1, right=1
2025-12-02 13:34:20,765 - WARNING - Depth 10, feature X, threshold -0.404040404040404, left=1, right=6
2025-12-02 13:34:20,766 - WARNING - Depth 11, feature X, threshold -0.20202020202020154, left=1, right=5
2025-12-02 13:34:20,766 - WARNING - Depth 12, feature X, threshold 0.6060606060606064, left=4, right=1
2025-12-02 13:34:20,766 - WARNING - Depth 13, feature X, threshold 0.20202020202020154, left=2, right=2
2025-12-02 13:34:20,767 - WARNING - Depth 14, feature X, threshold 0.0, left=1, right=1
2025-12-02 13:34:20,767 - WARNING - Depth 14, feature X, threshold 0.404040404040404, left=1, right=1
2025-12-02 13:34:20,768 - WARNING - Depth 6, feature X, threshold 2.6262626262626254, left=9, right=1
2025-12-02 13:34:20,768 - WARNING - Depth 7, feature X, threshold 1.616161616161616, left=4, right=5
2025-12-02 13:34:20,768 - WARNING - Depth 8, feature X, threshold 1.0101010101010095, left=1, right=3
2025-12-02 13:34:20,769 - WARNING - Depth 9, feature X, threshold 1.4141414141414144, left=2, right=1
2025-12-02 13:34:20,769 - WARNING - Depth 10, feature X, threshold 1.212121212121212, left=1, right=1
2025-12-02 13:34:20,770 - WARNING - Depth 8, feature X, threshold 1.8181818181818175, left=1, right=4
2025-12-02 13:34:20,770 - WARNING - Depth 9, feature X, threshold 2.2222222222222223, left=2, right=2
2025-12-02 13:34:20,771 - WARNING - Depth 10, feature X, threshold 2.02020202020202, left=1, right=1
2025-12-02 13:34:20,771 - WARNING - Depth 10, feature X, threshold 2.424242424242424, left=1, right=1
2025-12-02 13:34:20,772 - WARNING - Depth 5, feature X, threshold 3.4343434343434343, left=3, right=2
2025-12-02 13:34:20,772 - WARNING - Depth 6, feature X, threshold 3.2323232323232327, left=2, right=1
2025-12-02 13:34:20,773 - WARNING - Depth 7, feature X, threshold 3.0303030303030303, left=1, right=1
2025-12-02 13:34:20,773 - WARNING - Depth 6, feature X, threshold 3.636363636363636, left=1, right=1
2025-12-02 13:34:20,774 - WARNING - Depth 3, feature X, threshold 5.656565656565657, left=9, right=6
2025-12-02 13:34:20,774 - WARNING - Depth 4, feature X, threshold 4.040404040404041, left=1, right=8
2025-12-02 13:34:20,774 - WARNING - Depth 5, feature X, threshold 4.848484848484849, left=4, right=4
2025-12-02 13:34:20,775 - WARNING - Depth 6, feature X, threshold 4.646464646464646, left=3, right=1
2025-12-02 13:34:20,775 - WARNING - Depth 7, feature X, threshold 4.444444444444444, left=2, right=1
2025-12-02 13:34:20,776 - WARNING - Depth 8, feature X, threshold 4.242424242424242, left=1, right=1
2025-12-02 13:34:20,776 - WARNING - Depth 6, feature X, threshold 5.05050505050505, left=1, right=3
2025-12-02 13:34:20,777 - WARNING - Depth 7, feature X, threshold 5.454545454545454, left=2, right=1
2025-12-02 13:34:20,777 - WARNING - Depth 8, feature X, threshold 5.252525252525252, left=1, right=1
2025-12-02 13:34:20,778 - WARNING - Depth 4, feature X, threshold 6.262626262626263, left=3, right=3
2025-12-02 13:34:20,778 - WARNING - Depth 5, feature X, threshold 6.0606060606060606, left=2, right=1
2025-12-02 13:34:20,778 - WARNING - Depth 6, feature X, threshold 5.858585858585858, left=1, right=1
2025-12-02 13:34:20,779 - WARNING - Depth 5, feature X, threshold 6.666666666666666, left=2, right=1
2025-12-02 13:34:20,779 - WARNING - Depth 6, feature X, threshold 6.464646464646464, left=1, right=1
2025-12-02 13:34:20,780 - WARNING - Depth 1, feature X, threshold 8.282828282828282, left=7, right=9
2025-12-02 13:34:20,780 - WARNING - Depth 2, feature X, threshold 7.878787878787879, left=5, right=2
2025-12-02 13:34:20,781 - WARNING - Depth 3, feature X, threshold 7.474747474747474, left=3, right=2
2025-12-02 13:34:20,781 - WARNING - Depth 4, feature X, threshold 7.070707070707071, left=1, right=2
2025-12-02 13:34:20,782 - WARNING - Depth 5, feature X, threshold 7.272727272727273, left=1, right=1
2025-12-02 13:34:20,782 - WARNING - Depth 4, feature X, threshold 7.6767676767676765, left=1, right=1
2025-12-02 13:34:20,783 - WARNING - Depth 3, feature X, threshold 8.08080808080808, left=1, right=1
2025-12-02 13:34:20,783 - WARNING - Depth 2, feature X, threshold 9.494949494949495, left=6, right=3
2025-12-02 13:34:20,783 - WARNING - Depth 3, feature X, threshold 8.686868686868687, left=2, right=4
2025-12-02 13:34:20,784 - WARNING - Depth 4, feature X, threshold 8.484848484848484, left=1, right=1
2025-12-02 13:34:20,784 - WARNING - Depth 4, feature X, threshold 9.09090909090909, left=2, right=2
2025-12-02 13:34:20,785 - WARNING - Depth 5, feature X, threshold 8.88888888888889, left=1, right=1
2025-12-02 13:34:20,785 - WARNING - Depth 5, feature X, threshold 9.292929292929292, left=1, right=1
2025-12-02 13:34:20,786 - WARNING - Depth 3, feature X, threshold 9.696969696969697, left=1, right=2
2025-12-02 13:34:20,786 - WARNING - Depth 4, feature X, threshold 9.8989898989899, left=1, right=1

Empty DataFrame
Columns: [0]
Index: []

In [60]:
# compare what happens if decoded! 
testTree = RegressionTreeNico()
sk_tree = DecisionTreeRegressor(random_state=42)

data_encoded = pd.get_dummies(df[["season", "holiday", "weekday", "weathersit"]], drop_first=True)
data_encoded2 = pd.get_dummies(
    df, 
    columns=["season", "holiday", "weekday", "weathersit"], 
    drop_first=True
)

treee = testTree.fit(data_encoded2, categorical_features=["season", "holiday", "weekday", "weathersit"], target_name= "cnt")
y_pred_custom = treee.predict(pd.DataFrame(data_encoded2.drop("cnt", axis=1)))

sk_tree.fit(data_encoded, df["cnt"])
y_pred = sk_tree.predict(data_encoded)

check = pd.DataFrame(pd.Series(y_pred) == y_pred_custom)
check[check[0] == False]

2025-12-02 13:34:22,311 - WARNING - Depth 0, feature weathersit_3, threshold 0.0, left=710, right=21
2025-12-02 13:34:22,322 - WARNING - Depth 1, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,326 - WARNING - Depth 2, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,328 - WARNING - Depth 3, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,330 - WARNING - Depth 4, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,333 - WARNING - Depth 5, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,335 - WARNING - Depth 6, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,339 - WARNING - Depth 7, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,343 - WARNING - Depth 8, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,347 - WARNING - Depth 9, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,349 - WARNING - Depth 10, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,352 - WARNING - Depth 11, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,356 - WARNING - Depth 12, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,361 - WARNING - Depth 13, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,369 - WARNING - Depth 14, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,374 - WARNING - Depth 15, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,380 - WARNING - Depth 16, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,383 - WARNING - Depth 17, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,392 - WARNING - Depth 18, feature weathersit_3, threshold 0.0, left=710, right=0

2025-12-02 13:34:22,399 - WARNING - Depth 19, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,402 - WARNING - Depth 20, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,423 - WARNING - Depth 21, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,430 - WARNING - Depth 22, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,437 - WARNING - Depth 23, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,445 - WARNING - Depth 24, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,448 - WARNING - Depth 25, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,455 - WARNING - Depth 26, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,459 - WARNING - Depth 27, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,462 - WARNING - Depth 28, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,463 - WARNING - Depth 29, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,465 - WARNING - Depth 30, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,467 - WARNING - Depth 31, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,469 - WARNING - Depth 32, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,471 - WARNING - Depth 33, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,473 - WARNING - Depth 34, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,476 - WARNING - Depth 35, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,478 - WARNING - Depth 36, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,480 - WARNING - Depth 37, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,483 - WARNING - Depth 38, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,487 - WARNING - Depth 39, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,489 - WARNING - Depth 40, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,492 - WARNING - Depth 41, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,494 - WARNING - Depth 42, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,496 - WARNING - Depth 43, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,498 - WARNING - Depth 44, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,500 - WARNING - Depth 45, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,502 - WARNING - Depth 46, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,503 - WARNING - Depth 47, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,505 - WARNING - Depth 48, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,507 - WARNING - Depth 49, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,509 - WARNING - Depth 50, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,511 - WARNING - Depth 51, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,513 - WARNING - Depth 52, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,515 - WARNING - Depth 53, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,517 - WARNING - Depth 54, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,519 - WARNING - Depth 55, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,521 - WARNING - Depth 56, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,523 - WARNING - Depth 57, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,525 - WARNING - Depth 58, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,526 - WARNING - Depth 59, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,528 - WARNING - Depth 60, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,530 - WARNING - Depth 61, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,532 - WARNING - Depth 62, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,534 - WARNING - Depth 63, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,536 - WARNING - Depth 64, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,538 - WARNING - Depth 65, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,541 - WARNING - Depth 66, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,542 - WARNING - Depth 67, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,544 - WARNING - Depth 68, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,546 - WARNING - Depth 69, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,548 - WARNING - Depth 70, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,550 - WARNING - Depth 71, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,552 - WARNING - Depth 72, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,554 - WARNING - Depth 73, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,555 - WARNING - Depth 74, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,557 - WARNING - Depth 75, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,559 - WARNING - Depth 76, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,561 - WARNING - Depth 77, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,563 - WARNING - Depth 78, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,565 - WARNING - Depth 79, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,567 - WARNING - Depth 80, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,568 - WARNING - Depth 81, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,570 - WARNING - Depth 82, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,572 - WARNING - Depth 83, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,574 - WARNING - Depth 84, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,576 - WARNING - Depth 85, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,578 - WARNING - Depth 86, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,581 - WARNING - Depth 87, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,583 - WARNING - Depth 88, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,588 - WARNING - Depth 89, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,591 - WARNING - Depth 90, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,594 - WARNING - Depth 91, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,597 - WARNING - Depth 92, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,599 - WARNING - Depth 93, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,602 - WARNING - Depth 94, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,609 - WARNING - Depth 95, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,611 - WARNING - Depth 96, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,613 - WARNING - Depth 97, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,615 - WARNING - Depth 98, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,617 - WARNING - Depth 99, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,619 - WARNING - Depth 100, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,623 - WARNING - Depth 101, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,625 - WARNING - Depth 102, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,627 - WARNING - Depth 103, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,629 - WARNING - Depth 104, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,631 - WARNING - Depth 105, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,633 - WARNING - Depth 106, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,634 - WARNING - Depth 107, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,637 - WARNING - Depth 108, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,639 - WARNING - Depth 109, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,641 - WARNING - Depth 110, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,643 - WARNING - Depth 111, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,645 - WARNING - Depth 112, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,647 - WARNING - Depth 113, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,649 - WARNING - Depth 114, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,651 - WARNING - Depth 115, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,653 - WARNING - Depth 116, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,655 - WARNING - Depth 117, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,657 - WARNING - Depth 118, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,659 - WARNING - Depth 119, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,661 - WARNING - Depth 120, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,663 - WARNING - Depth 121, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,665 - WARNING - Depth 122, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,666 - WARNING - Depth 123, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,668 - WARNING - Depth 124, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,670 - WARNING - Depth 125, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,672 - WARNING - Depth 126, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,674 - WARNING - Depth 127, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,676 - WARNING - Depth 128, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,677 - WARNING - Depth 129, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,679 - WARNING - Depth 130, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,681 - WARNING - Depth 131, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,683 - WARNING - Depth 132, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,685 - WARNING - Depth 133, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,686 - WARNING - Depth 134, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,688 - WARNING - Depth 135, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,690 - WARNING - Depth 136, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,692 - WARNING - Depth 137, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,695 - WARNING - Depth 138, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,697 - WARNING - Depth 139, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,701 - WARNING - Depth 140, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,703 - WARNING - Depth 141, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,706 - WARNING - Depth 142, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,708 - WARNING - Depth 143, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,710 - WARNING - Depth 144, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,711 - WARNING - Depth 145, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,713 - WARNING - Depth 146, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,715 - WARNING - Depth 147, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,717 - WARNING - Depth 148, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,719 - WARNING - Depth 149, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,721 - WARNING - Depth 150, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,723 - WARNING - Depth 151, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,725 - WARNING - Depth 152, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,727 - WARNING - Depth 153, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,728 - WARNING - Depth 154, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,730 - WARNING - Depth 155, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,732 - WARNING - Depth 156, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,734 - WARNING - Depth 157, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,736 - WARNING - Depth 158, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,738 - WARNING - Depth 159, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,739 - WARNING - Depth 160, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,741 - WARNING - Depth 161, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,743 - WARNING - Depth 162, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,745 - WARNING - Depth 163, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,747 - WARNING - Depth 164, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,749 - WARNING - Depth 165, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,750 - WARNING - Depth 166, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,752 - WARNING - Depth 167, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,754 - WARNING - Depth 168, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,756 - WARNING - Depth 169, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,758 - WARNING - Depth 170, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,760 - WARNING - Depth 171, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,762 - WARNING - Depth 172, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,764 - WARNING - Depth 173, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,766 - WARNING - Depth 174, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,768 - WARNING - Depth 175, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,770 - WARNING - Depth 176, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,772 - WARNING - Depth 177, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,773 - WARNING - Depth 178, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,775 - WARNING - Depth 179, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,777 - WARNING - Depth 180, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,779 - WARNING - Depth 181, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,781 - WARNING - Depth 182, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,783 - WARNING - Depth 183, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,785 - WARNING - Depth 184, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,787 - WARNING - Depth 185, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,789 - WARNING - Depth 186, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,791 - WARNING - Depth 187, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,793 - WARNING - Depth 188, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,796 - WARNING - Depth 189, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,798 - WARNING - Depth 190, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,802 - WARNING - Depth 191, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,805 - WARNING - Depth 192, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,807 - WARNING - Depth 193, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,812 - WARNING - Depth 194, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,814 - WARNING - Depth 195, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,816 - WARNING - Depth 196, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,818 - WARNING - Depth 197, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,820 - WARNING - Depth 198, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,822 - WARNING - Depth 199, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,824 - WARNING - Depth 200, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,826 - WARNING - Depth 201, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,828 - WARNING - Depth 202, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,830 - WARNING - Depth 203, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,831 - WARNING - Depth 204, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,833 - WARNING - Depth 205, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,835 - WARNING - Depth 206, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,837 - WARNING - Depth 207, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,839 - WARNING - Depth 208, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,841 - WARNING - Depth 209, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,842 - WARNING - Depth 210, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,844 - WARNING - Depth 211, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,846 - WARNING - Depth 212, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,848 - WARNING - Depth 213, feature weathersit_3, threshold 0.0, left=710, right=0
2025-12-02 13:34:22,850 - WARNING - Depth 214, feature weathersit_3, threshold 0.0, left=710, right=0

RecursionError: maximum recursion depth exceeded

KeyboardInterrupt:

In [ ]:
def print_tree(tree: dict, depth: int = 0):
    """
    Recursively prints the custom regression tree structure in a readable format.

    This is GPTs doing as I did not bother printing stuff now
    """
    indent = "  " * depth

    # Continuous split
    if "threshold" in tree:
        print(f"{indent}Feature: {tree['feature']} <= {tree['threshold']}")
        if isinstance(tree["left"], dict):
            print(f"{indent}--> Left:")
            print_tree(tree["left"], depth + 1)
        else:
            print(f"{indent}--> Left leaf: {tree['left']:.3f}")

        print(f"{indent}Feature: {tree['feature']} > {tree['threshold']}")
        if isinstance(tree["right"], dict):
            print(f"{indent}--> Right:")
            print_tree(tree["right"], depth + 1)
        else:
            print(f"{indent}--> Right leaf: {tree['right']:.3f}")

    # Categorical split
    elif "branches" in tree:
        print(f"{indent}Feature: {tree['feature']} (categorical)")
        for val, branch in tree["branches"].items():
            if isinstance(branch, dict):
                print(f"{indent}--> Value {val}:")
                print_tree(branch, depth + 1)
            else:
                print(f"{indent}--> Value {val} leaf: {branch:.3f}")

Feature: X1 <= 3.5
--> Left:
  Feature: X1 <= 2.5
  --> Left leaf: 1.500
  Feature: X1 > 2.5
  --> Right leaf: 3.000
Feature: X1 > 3.5
--> Right:
  Feature: X1 <= 4.5
  --> Left leaf: 3.900
  Feature: X1 > 4.5
  --> Right leaf: 5.650